version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\polyfempy
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Release
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.x" # currently 3.6.8
    PYTHON_ARCH: "64"

  # - config: Release
  #   PYTHON: "C:\\Python35-x64"
  #   PYTHON_VERSION: "3.5.x" # currently 3.5.8
  #   PYTHON_ARCH: "64"

  # - config: Release
  #   PYTHON: "C:\\Python27-x64"
  #   PYTHON_VERSION: "2.7.x" # currently 2.7.15
  #   PYTHON_ARCH: "64"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install numpy"
build:
  parallel: true
build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cd c:\projects\polyfempy
  - "python --version"
  - python -m pip install . --no-deps -vv

test_script:
  - cd c:\projects\polyfempy
  - python tests/bending.py
  - python tests/gravity.py
  - python tests/inflation.py
  - python tests/plane_hole.py
  - python tests/torsion.py