language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
  # - osx
addons:
  apt:
    packages:
    - libc++-dev
env:
  - CC=gcc CXX=g++
  - CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++"
install:
  - pip install numpy
  - pip install plotly
script:
  - python setup.py test
